/* NOTE this file is autogenerated by Scalate : see http://scalate.fusesource.org/ */

import _root_.scala.collection.JavaConversions._
import _root_.org.fusesource.scalate.support.TemplateConversions._
import _root_.org.fusesource.scalate.util.Measurements._
import org.fusesource.scalate.wikitext.PygmentizeHelpers._

object $_scalate_$stations_ssp {
  def $_scalate_$render($_scalate_$_context: _root_.org.fusesource.scalate.RenderContext): Unit = {
    ;{
      implicit val context: _root_.org.fusesource.scalate.servlet.ServletRenderContext = $_scalate_$_context.attribute("context")
      import context._
      
      
      ;{
        val stations: List[com.scalate.samples.model.Station] = $_scalate_$_context.attribute("stations")
        $_scalate_$_context << ( "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n<stations>\r\n" );
        for (        station <- stations
) {
          $_scalate_$_context << ( "\t<station lat=\"" );
          $_scalate_$_context <<< (           station.lat
 );
          $_scalate_$_context << ( "\" long=\"" );
          $_scalate_$_context <<< (           station.long
 );
          $_scalate_$_context << ( "\">" );
          $_scalate_$_context <<< (           station.name
 );
          $_scalate_$_context << ( "</station>\r\n" );
        }
        $_scalate_$_context << ( "</stations>" );
      }
    }
  }
}


class $_scalate_$stations_ssp extends _root_.org.fusesource.scalate.Template {
  def render(context: _root_.org.fusesource.scalate.RenderContext): Unit = $_scalate_$stations_ssp.$_scalate_$render(context)
}
